-- ============================================
-- DNA Personal Genome Intelligence v3.0 Schema
-- Longitudinal Memory + Health Timeline + Family Graph
-- ============================================

-- ClinVar import snapshots for tracking updates over time
CREATE TABLE IF NOT EXISTS clinvar_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    record_count INTEGER,
    version_tag TEXT
);

-- Track how variant evidence changes across ClinVar releases
CREATE TABLE IF NOT EXISTS variant_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    variant_id INTEGER NOT NULL,
    snapshot_id INTEGER,
    clinvar_significance TEXT,
    clinvar_review_status TEXT,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_type TEXT,
    previous_significance TEXT,
    FOREIGN KEY (variant_id) REFERENCES variants(id),
    FOREIGN KEY (snapshot_id) REFERENCES clinvar_snapshots(id)
);

-- User-facing alerts generated by the system
CREATE TABLE IF NOT EXISTS user_alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_name TEXT NOT NULL,
    variant_id INTEGER,
    alert_type TEXT,
    title TEXT,
    message TEXT,
    severity TEXT,
    is_read INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (variant_id) REFERENCES variants(id)
);

-- Unified health timeline: genome, labs, meds, wearables, symptoms, imaging
CREATE TABLE IF NOT EXISTS timeline_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_name TEXT NOT NULL,
    event_date TEXT NOT NULL,
    event_type TEXT,
    source TEXT,
    title TEXT,
    description TEXT,
    data_json TEXT,
    related_variant_id INTEGER,
    FOREIGN KEY (related_variant_id) REFERENCES variants(id)
);

-- Family members linked to a proband
CREATE TABLE IF NOT EXISTS family_members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    proband_sample TEXT NOT NULL,
    relation TEXT NOT NULL,
    name TEXT,
    sex TEXT,
    affected INTEGER DEFAULT 0,
    conditions TEXT,
    has_genome INTEGER DEFAULT 0,
    sample_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Computed family risks based on proband findings
CREATE TABLE IF NOT EXISTS family_risks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    proband_sample TEXT NOT NULL,
    family_member_id INTEGER,
    gene_symbol TEXT,
    variant_id INTEGER,
    risk_type TEXT,
    probability REAL,
    recommendation TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (variant_id) REFERENCES variants(id),
    FOREIGN KEY (family_member_id) REFERENCES family_members(id)
);

-- Medication history for interaction checking
CREATE TABLE IF NOT EXISTS user_medications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_name TEXT NOT NULL,
    drug_name TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    dosage TEXT,
    frequency TEXT,
    prescribed_by TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Lab results history
CREATE TABLE IF NOT EXISTS lab_results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sample_name TEXT NOT NULL,
    test_date TEXT NOT NULL,
    test_name TEXT NOT NULL,
    value REAL,
    unit TEXT,
    reference_range TEXT,
    is_abnormal INTEGER DEFAULT 0,
    source_file TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
